export enum EmitterEvent {
  CHECKPOINT_FINALIZED = 'CHECKPOINT_FINALIZED',
  TRANSFER_COMPLETE = 'TRANSFER_COMPLETE',
  SYNC_STARTED = 'SYNC_STARTED',
  SYNC_FINISHED = 'SYNC_FINISHED',
  EXIT_FINALIZED = 'EXIT_FINALIZED'
}

export enum UserActionEvent {
  DEPOSIT = 'DEPOSIT',
  SEND = 'SEND',
  RECIEVE = 'RECIEVE',
  EXIT = 'EXIT'
}
