export enum EmitterEvent {
  CHECKPOINT_FINALIZED = 'CHECKPOINT_FINALIZED',
  TRANSFER_COMPLETE = 'TRANSFER_COMPLETE',
  SYNC_BLOCK_STARTED = 'SYNC_BLOCK_STARTED',
  SYNC_BLOCK_FINISHED = 'SYNC_BLOCK_FINISHED',
  SYNC_BLOCKS_STARTED = 'SYNC_BLOCKS_STARTED',
  SYNC_BLOCKS_FINISHED = 'SYNC_BLOCKS_FINISHED',
  EXIT_FINALIZED = 'EXIT_FINALIZED'
}

export enum UserActionEvent {
  DEPOSIT = 'DEPOSIT',
  SEND = 'SEND',
  RECIEVE = 'RECIEVE',
  EXIT = 'EXIT'
}
